apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ss-tag
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: localhost:27017
  - name: keyPrefix
    value: table-amorphie-tag



