FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" amorphie-taguser && chown -R amorphie-taguser:amorphie-taguser /app
USER amorphie-taguser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./amorphie.tag.migrate/amorphie.tag.migrate.csproj", "."]
RUN dotnet restore "./amorphie.tag.migrate.csproj"
COPY . .
WORKDIR "/src/."

RUN dotnet build "./amorphie.tag.migrate/amorphie.tag.migrate.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.tag.migrate/amorphie.tag.migrate.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "amorphie.tag.migrate.dll"]
