FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app


RUN adduser -u 5679 --disabled-password --gecos "" amorphie-executeuser && chown -R amorphie-executeuser:amorphie-executeuser /app
USER amorphie-executeuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false
COPY ["./amorphie.tag.execute/amorphie.tag.execute.csproj", "."]
RUN dotnet restore "./amorphie.tag.execute.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.tag.execute/amorphie.tag.execute.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.tag.execute/amorphie.tag.execute.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.tag.execute.dll"]
