FROM mcr.microsoft.com/dotnet/aspnet:8.0.2 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" amorphie-taguser && chown -R amorphie-taguser:amorphie-taguser /app
USER amorphie-taguser

FROM mcr.microsoft.com/dotnet/sdk:8.0.200 AS build
WORKDIR /src
ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false
COPY ["./amorphie.tag/amorphie.tag.csproj", "."]
RUN dotnet restore "./amorphie.tag.csproj"
COPY . .
WORKDIR "/src/."

RUN dotnet build "./amorphie.tag/amorphie.tag.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.tag/amorphie.tag.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY ["../amorphie.tag.data/Migrations", "./Migrations"]
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.tag.dll"]
