
GET http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag HTTP/1.1

###
GET http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag?pagesize=1 HTTP/1.1

###
GET http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag?pagesize=2&page=2 HTTP/1.1

###
GET http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag/retail-customer HTTP/1.1

###
POST http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag HTTP/1.1
Content-Type: application/json

{
    "Name":"idm",
    "Url":"-",
    "Ttl":161
}

###
POST http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag/retail-customer/tags HTTP/1.1
Content-Type: application/json
"idm"

###
DELETE http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag/retail-customer HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:40001/v1.0/invoke/amorphie-tag/method/tag/retail-customer/tags/idm HTTP/1.1
Content-Type: application/json