apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: amorphie-cache
  namespace: amorphie-tag-execute
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis-cluster.redis-amorphie.svc.cluster.local:6379"
  - name: redisPassword
    secretKeyRef:
      name: test-redis-secret
      key: redis-password
  - name: actorStateStore
    value: "true"
  - name: redisType
    value: "cluster"
  - name: keyPrefix
    value: name
auth:
  secretStore: amorphie-secretstore

